import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
import Dock from "@/components/Dock";


const myFont = localFont({
  src: "../../public/font/font.ttf",
  variable: "--font-plus-jakarta-sans",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.className} bg-smoky text-floral bg-gray-100 min-h-screen flex flex-col items-center`}
      >
        <Navbar />
        <main className="min-h-[calc(100vh-8rem)] flex flex-col">
          {children}
        </main>
        <Dock />
      </body>
    </html>
  );
}
